# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, help_text='邮件', max_length=254, null=True, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(blank=True, help_text='名称', max_length=20, null=True, verbose_name='名称'),
        ),
    ]
