# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 20:07
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_articles_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章详情'),
        ),
    ]
