# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190624_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='commentUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='postComents', to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
    ]
