# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_gamesreviews_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '用户评论', 'verbose_name_plural': '用户评论'},
        ),
        migrations.AlterModelOptions(
            name='gamesreviews',
            options={'verbose_name': '游戏信息', 'verbose_name_plural': '游戏信息'},
        ),
        migrations.AddField(
            model_name='gamesreviews',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否主页'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
    ]
