# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articles_commentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='commentUser',
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='articleimage', verbose_name='文章主图片'),
        ),
    ]
