# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190619_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesreviews',
            name='backImage',
            field=models.ImageField(default='', upload_to='gameimage', verbose_name='游戏背景图'),
        ),
    ]
