# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_gamesreviews_backimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesreviews',
            name='isRecom',
            field=models.BooleanField(default=False, verbose_name='编辑推荐'),
        ),
    ]
