# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_gamesreviews_isrecom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名字', max_length=20, verbose_name='名字')),
                ('email', models.EmailField(help_text='邮箱', max_length=254, verbose_name='邮箱')),
                ('obj', models.CharField(help_text='主题', max_length=50, verbose_name='主题')),
                ('text', models.TextField(help_text='内容', verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
    ]
